# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XD
  
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'

  # Networking
  pod 'KeychainSwift'
  pod 'Moya'

  # UI
  pod 'FloatingPanel'
  pod 'SnapKit'
  pod 'DropDown'
  pod 'Then'

  # Others
  pod 'SwiftLint'
  pod 'R.swift' 
end
